### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by markusbkk** [dudykr/stc#156]
Just wondering how to use `stc`, at its current state.
Do I need to consume it as a library or run it through a test shim?

I cloned the repository, updated the dependencies through `yarn` and compiled the project with `rustc build`.
Alas, the resulting `stc` binary only contains two subcommands (**help** and **iterate**) and simply providing a TypeScript source file simply returns a `Found argument '<pathToTSFile>' which wasn't expected, or isn't valid in this context`

**Comment by kdy1** [comment]
It's under active development

**Comment by bcheidemann** [comment]
@markusbkk depends what you mean by 'use'. It's trivial to implement a new command (e.g. `stc check <file-path>`). You will need to update https://github.com/dudykr/stc/blob/main/src/main.rs and https://github.com/dudykr/stc/blob/main/src/check.rs. But as @kdy1 says, it's under active development so there is currently no way to use it like you would `tsc`.

**Comment by markusbkk** [comment]
> @markusbkk depends what you mean by 'use'. It's trivial to implement a new command (e.g. `stc check <file-path>`). You will need to update https://github.com/dudykr/stc/blob/main/src/main.rs and https://github.com/dudykr/stc/blob/main/src/check.rs. But as @kdy1 says, it's under active development so there is currently no way to use it like you would `tsc`.

Understood

I wasn't aware that it was still very much pre-alpha
