### ISSUE TITLE
Handle assignment of tuples with rest

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#172]
I postponed it from https://github.com/dudykr/stc/pull/170 because I have another item to work on

Basically, 
```ts
//@strict: true

type ArgsUnion = [number, string] | [number, Error];
type TupleUnionFunc = (...params: ArgsUnion) => number;

const funcUnionTupleRest: TupleUnionFunc = (...params) => {
  const [num, strOrErr] = params;
  return num;
};


export { }
```

should work.

It can be done by fixing code at https://github.com/dudykr/stc/blob/9efde34c022210e33df519c6f324bb62ad521abc/crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs#L2000-L2011 to handle an element with rest type specially.

**Comment by Camc314** [comment]
@kdy1 I'll give this a shot

**Comment by kdy1** [comment]
Thanks!
