### ISSUE TITLE
Append `undefined` to type list on optional member access

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#175]
https://github.com/dudykr/stc/blob/e69d14c1b30473f73bc8873400e950d44a047e64/crates/stc_ts_file_analyzer/tests/pass/exprs/optionalChaining/.access-6.ts#L2-L3

The type of `o6<number>()?.["x"];` above should be `number | undefined`, but currently it's `number`.

Relevant code for optional chaining is  https://github.com/dudykr/stc/blob/e69d14c1b30473f73bc8873400e950d44a047e64/crates/stc_ts_file_analyzer/src/analyzer/expr/optional_chaining.rs#L25-L49

**Comment by nissy-dev** [comment]
Hi 👋🏻 I'd like to work on this one as my first contribution! Can I take this issue?

**Comment by kdy1** [comment]
Of course, and thank you!

**Comment by nissy-dev** [comment]
I look into codes and found type inference of arrow function with generics cause this issue.

Currently, type inference of arrow function with generics is wrong.

```
declare const o6: <T>() => undefined | { x: number };
const x = o6<number>();  // type checker infer { x: number }
```

Then I read more codes, calculation for return type is in `get_return_type` of call_new.rs. I will try to fix some code of them.
`get_return_type` is very complex, so please let me know if you have any advice :pray:

**Comment by kdy1** [comment]
`get_return_type` calls `infer_arg_types` to infer types.

https://github.com/dudykr/stc/blob/d121f20feb4f7a66e96a1b093dfadc507baf8610/crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs#L77-L86

`infer_arg_types` has a logic to *prefer* the type annotation provided by the user, but I'm not sure why it's not working.

https://github.com/dudykr/stc/blob/d121f20feb4f7a66e96a1b093dfadc507baf8610/crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs#L96-L103

Maybe `base` is wrong? It is a rough guess, though.

**Comment by nissy-dev** [comment]
Thanks!  I seem undefined type is removed from return types after simplifying. I will dig into simplify method.


<img width="754" alt="SS_ 2022-11-04 23 34 03" src="https://user-images.githubusercontent.com/17228098/200001353-1bbe7a37-3981-4e2a-a978-a120aef9590c.png">

**Comment by kdy1** [comment]
Yeah I think you are right. I'm not sure why there's such logic. Maybe we need to remove the logic and check for regressions by invoking `check.sh`
