### ISSUE TITLE
Change error code for missing `new` for classes

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#178]
https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/forgottenNew.ts#L1-L5

The code above should fail with `TS2348`, but currently it failes with `TS2349`

<img width="821" alt="image" src="https://user-images.githubusercontent.com/29931815/199718373-e5092a8f-dbfa-4a45-84fa-d3a1a869b876.png">

It has the context of `tried to calculate return type`, which is used at

https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs#L1973-L1977

But error is `NoCallablePropertyWithName`, which is `TS2349`, and

<img width="821" alt="image" src="https://user-images.githubusercontent.com/29931815/199718717-4771860b-75f5-4da4-a3b0-9a8218fd2bb6.png">

---

So we should modify

https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs#L821-L825

to use different error variant.

**Comment by mrkldshv** [comment]
Hey! I'd like to work on this issue.

**Comment by kdy1** [comment]
Thanks!

**Comment by mrkldshv** [comment]
Just to be sure: to accomplish this we need to create new error type in `crates/stc_ts_errors/src/lib.rs`, map it to correct code (`TS2348`), and then change the error in `crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs`. Is that correct?

**Comment by kdy1** [comment]
Yeap, exactly

**Comment by mrkldshv** [comment]
Great, thanks for confirming! Is there any convention for errors' naming?

**Comment by kdy1** [comment]
No, but I think we need to refactor them in the future

**Comment by mrkldshv** [comment]
From the debugging I see that we are getting this error
https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs#L816 instead of https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs#L821
Is this behaviour correct? Did you mean to change the former error?

**Comment by kdy1** [comment]
This is incorrect, because `NoNewSignature` should be converted to another error.
It should be `NoConstructorPropertyWithName` I guess

**Comment by kdy1** [comment]
And `NoConstructorPropertyWithName` should have error code of `TS2348`

**Comment by kdy1** [comment]
The problematic part is the conversion of `NoNewSignature` to `NoCallablePropertyWithName`.
I think it should be `NoConstructablePropertyWithName` instead

**Comment by mrkldshv** [comment]
I see. Is that okay if the test won't pass after the changes though?

**Comment by kdy1** [comment]
Reducing matched_errors is  fine but increasing extra_errors or panic is not fine
