### ISSUE TITLE
Allow assignment of tuples with different length if it's `undefined` or `any`

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#181]
https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringArrayBindingPatternAndAssignment3.ts#L9-L10

This line should not report an argumentnt error because fields are optional.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/29931815/199725700-b951ae74-a89b-4d3c-bbf6-17828a638fad.png">

The type of arguments are correctly inferred as `[any, any, any, any]` but we should allow assignment of `[1]` to `[any, any, any, any]`.

https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs#L1999-L2010

The assignment logic for tuple should be aware of `any` or `undefined` and allow the length to mismatch for these cases.

**Comment by Beraliv** [comment]
Hey @kdy1 !

Can I take this one? I'd like to work on it

**Comment by kdy1** [comment]
Of course, thank you!

**Comment by Beraliv** [comment]
Thanks to your comment @hyp3rflow (link 🔗 – https://github.com/dudykr/stc/issues/179#issuecomment-1302211895).

I've also decided to double check error list in TypeScript repo and it's exactly the same (conformance tests are also identical):

* TypeScript – [destructuringArrayBindingPatternAndAssignment3.errors.txt](https://github.com/microsoft/TypeScript/blob/main/tests/baselines/reference/destructuringArrayBindingPatternAndAssignment3.errors.txt)
* stc - [destructuringArrayBindingPatternAndAssignment3.errors.json](https://github.com/dudykr/stc/blob/main/crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringArrayBindingPatternAndAssignment3.errors.json)

So tests are up-to-date

**Comment by Beraliv** [comment]
Now I'm trying to understand how I can run one specific test and get the same output that you shared on the screenshot

### Working with output

I've checked the typical flow in [CONTRIBUTING.md](https://github.com/dudykr/stc/blob/main/CONTRIBUTING.md#typical-workflow), but it says:

>  Each error will contain lots of information required for debugging, with context: prefix. Read it, and if it's a wrong error, copy in to ./crates/stc_ts_file_analyzer/tests/pass.

Output is so huge, how can you work with it? Do you maybe write it to the file and read when `./scripts/check.sh` is completed? I'm running it in VSCode and it's impossible to read anything. I would really appreciate any advice here.

### Running single test

So even though I couldn't get `context:` when I ran `./scripts/check.sh`, I still created a file in `crates/stc_ts_file_analyzer/tests/pass`.

I called it `es6/destructuring/destructuringArrayBindingPatternAndAssignment3/.6.ts` – in this commit https://github.com/Beraliv/stc/commit/aa917fe078694bf97e37fcb4f2d82ad6880d7584

When I run `./scripts/check.sh`, it's still running all 500 tests but not the single one that I just added

Do I miss anything?

### Get the same output

As I see on the screenshot, there's a DebugContext and the error below.

Can you please navigate me what I need to do to see it as well?

**Comment by kdy1** [comment]
You have two options.
`./scripts/test.sh yourTestName` will work, but if you want to reduce it further, you can copy it to tests directory of the file analyzer

https://github.com/dudykr/stc/tree/2ab93ad46cd2683539300bde8f30c7bf89ac1e15/crates/stc_ts_file_analyzer/tests

**Comment by Beraliv** [comment]
> The type of arguments are correctly inferred as [any, any, any, any] 

I'm still thinking whether it should be `[any, any?, any?, any?]` instead? As default parameters mean that the parameter is optional. Do you have a representation for that?

**Comment by kdy1** [comment]
There's a representation, but any? is any

It's exactly the same type

**Comment by Beraliv** [comment]
> There's a representation, but any? is any
> 
> It's exactly the same type

Not exactly, the example is here – https://tsplay.dev/WvGJkw

1. `type A = [any, any, any, any];` – A has a fixed length, which equals to 4
2. `type B = [any, any?, any?, any?];` means tuple can be of length between 1 and 4

That's why assigning `[1] to type B will work, but won't work for type A

**Comment by kdy1** [comment]
Oh, then there's `Type::Optional`

**Comment by kdy1** [comment]
@Beraliv Are you actively working on it? I'm asking this because it's a good-first-issue

**Comment by Beraliv** [comment]
@kdy1, sorry for leaving no progress for 8 days. I struggled with the fix so wasn't sure how to proceed with it.

Is it possible you give me some hints?

I'm happy to continue with it, but if anyone already has a fix, I'm happy to let her/him do it instead of me

**Comment by Beraliv** [comment]
Just to be trasnparent, that's what I have now – https://github.com/dudykr/stc/pull/298

**Comment by Beraliv** [comment]
> You have two options. `./scripts/test.sh yourTestName` will work, but if you want to reduce it further, you can copy it to tests directory of the file analyzer
> 
> https://github.com/dudykr/stc/tree/2ab93ad46cd2683539300bde8f30c7bf89ac1e15/crates/stc_ts_file_analyzer/tests

I can confirm that for `crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringArrayBindingPatternAndAssignment3.ts` running `./scripts/test.sh destructuringArrayBindingPatternAndAssignment3` worked for me

Thank you again for the help!

**Comment by kdy1** [comment]
Do you still need help?

**Comment by Beraliv** [comment]
> Do you still need help?

Let me come back to you in the evening, as I'm on the conference today.

I will explain what I try to do and where I need to be navigated

**Comment by Beraliv** [comment]
I imagine any is implicit for function parameters so they're inferred as [any, any, any, any].

But as we have default parameters, I wonder if it would be possible to convert it to [any, any?, any?, any?].

If so, what is the best place to do it? Because for now I get `elems` already with the wrong type.

I know how to do it when it will be of a different type (match l as element of `elems` with Optional as you suggested above, if it's true for the rest of tuple, don't emit error - ✅)

So the confusing part for me is that place for inferring type for function parameters. Can you please navigate me in the codebase so I know where to make a change?

**Comment by kdy1** [comment]
Not sure. You can search for `RPat::Assign` using IDE to look at possible cases.

I expect it to be one of


https://github.com/dudykr/stc/blob/d8b849c672f033c1e0a04caf9737f9a6ae7c6863/crates/stc_ts_file_analyzer/src/analyzer/pat.rs#L144

https://github.com/dudykr/stc/blob/d8b849c672f033c1e0a04caf9737f9a6ae7c6863/crates/stc_ts_file_analyzer/src/analyzer/pat.rs#L276-L285

https://github.com/dudykr/stc/blob/d8b849c672f033c1e0a04caf9737f9a6ae7c6863/crates/stc_ts_file_analyzer/src/analyzer/pat.rs#L316-L374

https://github.com/dudykr/stc/blob/d8b849c672f033c1e0a04caf9737f9a6ae7c6863/crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs#L158-L217

https://github.com/dudykr/stc/blob/d8b849c672f033c1e0a04caf9737f9a6ae7c6863/crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs#L275-L291

**Comment by Beraliv** [comment]
I keep looking at it.

Was there any change to `main` branch? I pulled changes from there and I'm trying to rebuild it and I see errors:

```bash
➜ cargo install --path .
  Installing stc v0.1.0 (/Users/beraliv/Documents/Code/stc)
    Updating crates.io index
warning: unused import: `std::cell::RefCell`
 --> crates/stc_utils/src/error.rs:1:5
  |
1 | use std::cell::RefCell;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `crate::panic_context`
 --> crates/stc_utils/src/error.rs:3:5
  |
3 | use crate::panic_context;
  |     ^^^^^^^^^^^^^^^^^^^^

warning: unused imports: `cell::RefCell`, `panic`, `sync::Once`
 --> crates/stc_utils/src/panic_context.rs:1:11
  |
1 | use std::{cell::RefCell, panic, sync::Once};
  |           ^^^^^^^^^^^^^  ^^^^^  ^^^^^^^^^^

warning: `stc_utils` (lib) generated 3 warnings
   Compiling stc_ts_errors v0.1.0 (/Users/beraliv/Documents/Code/stc/crates/stc_ts_errors)
error[E0432]: unresolved import `crate::context::with_ctx`
  --> crates/stc_ts_errors/src/lib.rs:28:5
   |
28 | use crate::context::with_ctx;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `with_ctx` in `context`

warning: unused import: `std::cell::RefCell`
 --> crates/stc_ts_errors/src/context.rs:1:5
  |
1 | use std::cell::RefCell;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `rnode::RNode`
 --> crates/stc_ts_errors/src/debug/debugger.rs:3:5
  |
3 | use rnode::RNode;
  |     ^^^^^^^^^^^^

warning: unused import: `stc_ts_ast_rnode::RTsType`
 --> crates/stc_ts_errors/src/debug/debugger.rs:4:5
  |
4 | use stc_ts_ast_rnode::RTsType;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused imports: `Emitter`, `Node`, `text_writer::JsWriter`
 --> crates/stc_ts_errors/src/debug/debugger.rs:7:24
  |
7 | use swc_ecma_codegen::{text_writer::JsWriter, Emitter, Node};
  |                        ^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^  ^^^^

error[E0599]: no method named `push` found for unit type `()` in the current scope
  --> crates/stc_ts_errors/src/lib.rs:70:23
   |
70 |         self.contexts.push(context.to_string());
   |                       ^^^^ method not found in `()`

error[E0599]: no method named `iter` found for unit type `()` in the current scope
  --> crates/stc_ts_errors/src/lib.rs:90:34
   |
90 |         for ctx in self.contexts.iter().rev() {
   |                                  ^^^^ method not found in `()`

error[E0599]: no method named `push` found for unit type `()` in the current scope
    --> crates/stc_ts_errors/src/lib.rs:2002:43
     |
2002 |                         buf[idx].contexts.push(format!("duplicate: {}", e.contexts.join("\n")));
     |                                           ^^^^ method not found in `()`

error[E0599]: no method named `join` found for unit type `()` in the current scope
    --> crates/stc_ts_errors/src/lib.rs:2002:84
     |
2002 |                         buf[idx].contexts.push(format!("duplicate: {}", e.contexts.join("\n")));
     |                                                                                    ^^^^ method not found in `()`

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
warning: `stc_ts_errors` (lib) generated 4 warnings
error: could not compile `stc_ts_errors` due to 5 previous errors; 4 warnings emitted
error: failed to compile `stc v0.1.0 (/Users/beraliv/Documents/Code/stc)`, intermediate artifacts can be found at `/Users/beraliv/Documents/Code/stc/target`
```

Not sure if I'm doing something wrong

**Comment by Beraliv** [comment]
Thank you for merging the PR @kdy1!

I will keep looking at assignments and maybe raise a separate PR later this week to cover wider scope
