### ISSUE TITLE
Don't report an error on array pattern elements with a default value

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#182]
https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringArrayBindingPatternAndAssignment3.ts#L1

This should not error, but currently, stc emits `TupleIndexError`

<img width="733" alt="image" src="https://user-images.githubusercontent.com/29931815/199727757-5a11bba3-6131-40d3-8db2-844683b76057.png">

---

We should recover from the error based on the variant at https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs#L250-L263

**Comment by kdy1** [comment]
Everything required for fixing this is on the issue body.

Example code of error recover is

https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs#L1203-L1215

**Comment by kaf-lamed-beyt** [comment]
Great! Thanks for mentioning it, again.

**Comment by kaf-lamed-beyt** [comment]
I understand that the error log is due to this function here 👇🏼 

https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs#L250-L263

So now, my question is; what am I to do? I know the goal is to allow the restructuring assignment to pass the test. But, do I just go ahead and change the error message? What exactly do I need to do? 

I'd really love to get your feedback, @kdy1

**Comment by kdy1** [comment]
You should remove `?` and match on the result instead

**Comment by kaf-lamed-beyt** [comment]
Thanks! 

I'm having some set of blockers BTW. When I type `./scripts/check.sh` in my terminal, I'm presented with the error below 

![Screenshot from 2022-11-03 18-05-21](https://user-images.githubusercontent.com/48127194/199788909-7dcd2922-283b-467a-af62-9657169bcf98.png)

...and when I try to add my commit message. Some pre-commit hooks were fired. Here's the error I'm getting 👇🏼 

![Screenshot from 2022-11-03 18-09-37](https://user-images.githubusercontent.com/48127194/199789166-d43ac7e2-1996-4965-9f30-82755073f446.png)

**Comment by kdy1** [comment]
Did you install rust?

**Comment by kaf-lamed-beyt** [comment]
Oops! My bad!

I haven't. Lemme do that right away.

**Comment by kaf-lamed-beyt** [comment]
I've installed Rust on my machine, and I'm still getting the same error when I type `./scripts/check.sh`

Do I need to install any particular extension on VSCode?

**Comment by kdy1** [comment]
@kaf-lamed-beyt Are you working on it?

**Comment by kaf-lamed-beyt** [comment]
No, I'm stuck at where I need to push the changes

**Comment by kaf-lamed-beyt** [comment]
What do you think could be the issue? 

I have trust installed on my PC. But, when I try pushing, those pre-commit hooks still gets fired.

**Comment by kdy1** [comment]
Not sure because I don't know anything about it

**Comment by ever0de** [comment]
I implemented it with #202 , can you please let me know if I need to solve it in a different way?
