### ISSUE TITLE
Mark nested modules as valid LHS

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#184]
https://github.com/dudykr/stc/blob/2ab93ad46cd2683539300bde8f30c7bf89ac1e15/crates/stc_ts_type_checker/tests/conformance/expressions/valuesAndReferences/assignmentToParenthesizedIdentifiers.ts#L27-L29

The lines above should not report an error, but stc currently emits
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/29931815/199862708-331bf3c7-e7b5-45f8-b457-442650f3e64c.png">

The cause is

https://github.com/dudykr/stc/blob/2ab93ad46cd2683539300bde8f30c7bf89ac1e15/crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs#L936-L946

and it should be fixed to allow assignment to nested modules

**Comment by nyarthan** [comment]
Hey @kdy1 
I'd like to look at this!

**Comment by kdy1** [comment]
Cool, thank you!

**Comment by nyarthan** [comment]
@kdy1 I think I need some directions. I basically have to check if the exported vars of the nested module and the RHS match, is that correct?

**Comment by kdy1** [comment]
No, problem is that the assignment validation logic unconditionally emits an error if the LHS is a module

**Comment by kdy1** [comment]
Please read the body of the issue. I linked the problematic code.

**Comment by kdy1** [comment]
@nyarthan Are you working on it? Feel free to tell me if you want me to take it (or unassign)

**Comment by nyarthan** [comment]
@kdy1 Yes I'm working on it, if I don't find a solution soon I will let you know, I don't want to halt the progress..

**Comment by kdy1** [comment]
@n

**Comment by kdy1** [comment]
No worries, it's not urgent at all. I just wanted to ensure that good first issues are not assigned to someone who isn't going to work on it.

**Comment by kdy1** [comment]
@nyarthan Are you still working on it?

**Comment by kdy1** [comment]
Closing as fixed
