### ISSUE TITLE
Rest pattern should not trigger `TupleIndexErrror`

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#185]
https://github.com/dudykr/stc/blob/2ab93ad46cd2683539300bde8f30c7bf89ac1e15/crates/stc_ts_type_checker/tests/conformance/es6/destructuring/declarationsAndAssignments.ts#L180

The line above should not error because LHS is a rest pattern.
<img width="732" alt="image" src="https://user-images.githubusercontent.com/29931815/199899870-5138cdb8-832b-4ca0-9f8a-605655413646.png">

But currently stc fails with an error, because of the code below

https://github.com/dudykr/stc/blob/e59631e58fb04578142befb6e5dbc7ef1d52f9db/crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs#L250-L263

This is quite similar to https://github.com/dudykr/stc/issues/182, though.

**Comment by AlexMunoz** [comment]
Hi @kdy1, I'd love to work on this issue. Do you have any additional advice? Thanks.

**Comment by kdy1** [comment]
@AlexMunoz Basically, the problem is that we are returning errors from

```rust
             .with_context(|| { 
                 format!( 
                     "tried to get the type of {}th element from iterator to declare vars with an array pattern", 
                     idx 
                 ) 
             })? 
```

using `?` token. Instead of returning an error, we should recover from the error, based on the variant.
`Error#actual()` gives you the actually error value without context, so you can match on it.

**Comment by AlexMunoz** [comment]
Hey @kdy1 I think the PR https://github.com/dudykr/stc/pull/202  is also covering this case.

**Comment by kdy1** [comment]
Oh maybe. My bad, sorry
