### ISSUE TITLE
Type narrowing should handle object => class

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#190]
https://github.com/dudykr/stc/blob/d121f20feb4f7a66e96a1b093dfadc507baf8610/crates/stc_ts_type_checker/tests/conformance/types/nonPrimitive/nonPrimitiveNarrow.ts#L7-L10

The code above should succeed.

But the type checker infers the type of `a` in line 8 as `never` instead of `Narrow`.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/29931815/199997449-2e404b91-17a7-4ecf-b3ff-dff189a5d1b8.png">

Problematic code is at https://github.com/dudykr/stc/blob/d121f20feb4f7a66e96a1b093dfadc507baf8610/crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs#L349-L391

We should fix `narrow_with_instanceof` to support narrowing an object type to a class instance type.

**Comment by iheyunfei** [comment]
🙋‍♂️ I'd like to fix this.

**Comment by kdy1** [comment]
Thank you!
