### ISSUE TITLE
Template literal with `as const` should not be generalized as `string`

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#198]
# Problem

https://github.com/dudykr/stc/blob/18e24339e63c0de0e093fa0cc6683ebe4d3c860b/crates/stc_ts_type_checker/tests/conformance/types/literal/templateLiteralTypes3.ts#L20-L31

<img width="540" alt="image" src="https://user-images.githubusercontent.com/29931815/200098591-e5810052-47c5-4a4e-83f7-037d31863e3c.png">

`arg` should be `*${string}*` instead of `string.

---

# Solution

We have metadata named `prevent_generalization`.

https://github.com/dudykr/stc/blob/18e24339e63c0de0e093fa0cc6683ebe4d3c860b/crates/stc_ts_types/src/metadata.rs#L104

It's respected by literal => keyword pass, so the fix for the issue above will be making `*${s}* as const` have `prevent_generalization: true`.

**Comment by Windrushfarer** [comment]
Seems like a good start :) I'd like to take a look

**Comment by kdy1** [comment]
Thanks!

**Comment by kdy1** [comment]
@Windrushfarer Are you working on it? Feel free to tell me if you want me to take it (or unassign)

**Comment by Windrushfarer** [comment]
@kdy1 yes, I am still working. Sorry for the inconvenience, getting familiar with the codebase took a bit more time than I expected. I probably spotted the place to fix, will try it today or tomorrow maybe.

**Comment by kdy1** [comment]
No worries, it's not urgent at all. I just wanted to ensure that good first issues are not assigned to someone who isn't going to work on it.

**Comment by kdy1** [comment]
@Windrushfarer Are you still working on it?

**Comment by kdy1** [comment]
Closing as this is already fixed
