### ISSUE TITLE
Overlap validation of template literals is wrong

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#200]
# Problem

https://github.com/dudykr/stc/blob/18e24339e63c0de0e093fa0cc6683ebe4d3c860b/crates/stc_ts_type_checker/tests/conformance/types/literal/templateLiteralTypes3.ts#L132-L138

x (`foo-${string}`) and y (`${string}-bar`) have overlap, but stc fails to verify it.

# Solution

We should handle template literals specially in https://github.com/dudykr/stc/blob/18e24339e63c0de0e093fa0cc6683ebe4d3c860b/crates/stc_ts_file_analyzer/src/analyzer/expr/type_cast.rs#L234-L243

**Comment by feniljain** [comment]
Hey :wave:,

I was just exploring the issue to understand what exactly is going on, I realized for this case, `has_overlap` is not called at all currently, I traced back the call chain and to reach `validate` function [here](https://github.com/dudykr/stc/blob/798c322abf94b8353feb4f4022185b932069f5e1/crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs#L44). It seemed logical for it to be called cause it contains handling of `===`, but even `validate` is not called ( verified by keeping a `println` at start of `validate` )

Am I looking at completely wrong place? Any pointers would be help!

**Comment by kdy1** [comment]
`is_valid_for_switch_case` is used for `NoOverlap`, and it calls `has_overlap` in almost all cases, so what you said cannot happen. Are you sure that the test failed or you used `--nocapture`?

**Comment by feniljain** [comment]
I am surely not using `--nocapture`, though I did make some changes to test file, after shifting it to `stc_ts_file_analyzer/tests/pass`, I commented out complete file except the function mentioned above. And then left a `println` in `has_overlap`, but it didn't get printed :(

That's when I started looking into the call chain.
