### ISSUE TITLE
Handle `intrinsics` for template literal types

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#210]
https://github.com/dudykr/stc/blob/269f6c07676f728e667ca5fb4c80d7f17f66a98d/crates/stc_ts_type_checker/tests/conformance/types/literal/stringMappingOverPatternLiterals.ts#L2-L4

https://github.com/dudykr/stc/blob/269f6c07676f728e667ca5fb4c80d7f17f66a98d/crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs#L1551-L1610

We are handling `Type::Lit` (at line 1557), but we have to handle `Type:::Tpl`, too.

While handling `Type::Tpl`, we should return a new `Type::Tpl`. The expressions of `Type::Tpl` can be copied for string operations.

**Comment by ever0de** [comment]
```typescript
// templated
type ATemplate = `aA${string}`;
type BTemplate = Uppercase<ATemplate>;
type CTemplate = Lowercase<ATemplate>;
```
added to the test,
https://github.com/dudykr/stc/blob/269f6c07676f728e667ca5fb4c80d7f17f66a98d/crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs#L1551-L1610
### extend
```rust
                     Type::Tpl(TplType { quasis, types, .. }) => {
                         println!("quasis: {quasis:?}");
                         println!("types: {types:?}");

                         todo!()
                     }
```
Not caught in this code.

Maybe I got the test code wrong?

**Comment by kdy1** [comment]
Can you add a `dbg!(&arg.params[0])` at the above of https://github.com/dudykr/stc/blob/269f6c07676f728e667ca5fb4c80d7f17f66a98d/crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs#L1556 ?

Actually guessing data is a very hard task

**Comment by kdy1** [comment]
Ah, I found the cause. We are not calling `Analyzer.normalize()` for `arg.params[0]`

**Comment by ever0de** [comment]
https://github.com/ever0de/stc/blob/704d111de1519a1c8eebbc4aceab1cde682bf893/crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs#L1541-L1543

I tried this, but it doesn't work

1. It seems that map and typeof are not.
2. Do not normalize to interfaces.
3. Template literals, not generics.

So I set it to `Default::default`, um... yes... it doesn't work

**Comment by kdy1** [comment]
What do you mean by `fail` in 

> Let's make it fail

?

**Comment by ever0de** [comment]
```rust
     pub(crate) fn expand_intrinsic_types(&mut self, span: Span, ty: &Intrinsic) -> VResult {
         let arg = &ty.type_args;

         let binding = self.normalize(Some(span), Cow::Borrowed(&arg.params[0]), Default::default())?;
         let nom_ty: &Type = binding.borrow();
         dbg!(nom_ty);
         todo!();
```

Sorry for the lack of explanation.
Panic for every case, tried to see the types one by one

But this code is also ignored and returned.

**Comment by ever0de** [comment]
Oh no. I'm sorry.
New panic count in `conformance/types/literal/stringLiteralsAssignedToStringMappings.ts`.
Maybe I didn't see it because my VsCode update was slow...

I think I can find it now. i will solve it

**Comment by ever0de** [comment]
I'm watching a little
https://github.com/dudykr/stc/blob/71d3307952b3fa6501d90358813856f3da8b0ccb/crates/stc_ts_file_analyzer/src/analyzer/assign/tpl.rs#L25-L71
The current problem seems to be that I have to deal with `Intrinsic' here, am I in the wrong direction?

**Comment by kdy1** [comment]
No, intrinsics should be handled from https://github.com/dudykr/stc/blob/269f6c07676f728e667ca5fb4c80d7f17f66a98d/crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs#L1551-L1610

**Comment by ever0de** [comment]
Does it have nothing to do with the error coming out of the current test?
I think the location of making `context: tried to assign to a template type` is `analyzer/assign/tpl.rs`...

```
error[TS2322]: DebugContext(
     context:
     lhs = instanceof `A${string}`;
     rhs = intrinsic;
     context: tried to assign to a template type
     AssignFailed {
         span: span {
             lo: BytePos(
                 2856,
             ),
             hi: BytePos(
                 2863,
             ),
             ctxt: #6,
         },
         cause: [
             SimpleAssignFailed {
                 span: span {
                     lo: BytePos(
                         2856,
                     ),
                     hi: BytePos(
                         2863,
                     ),
                     ctxt: #6,
                 },
                 cause: None,
             },
         ],
     },
)
```

**Comment by kdy1** [comment]
Yes because the error is about the type after applying `normalize_for_assign` => `normalize` => `expand_intrinsic_types`.

Once you fix `expand_intrinsic_types`, the function for assigning will receive a correct type.

**Comment by ever0de** [comment]
In the current test case, `Type::Param` is the result of normalizing `arg.params[0]` in `expand_intrinsic_types`.
And this is what I think the original `arg.params[0]` is actually `Type::Param`.
```typescript
// templated
type ATemplate = `aA${string}`;
type BTemplate = Uppercase<ATemplate>;
type CTemplate = Lowercase<ATemplate>;
```
Here the `Uppercase` Intrinsic is receiving an `ATemplate`, which is a `Type::Param` .

In this case, should I change `Type::Param` to `Type::Intrinsic` in the `normalize` function below?
https://github.com/dudykr/stc/blob/d866515db67f4af3bfb4127f078156ceb7013064/crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs#L68

Or I can't come up with a way to receive `Tpl` from `expand_intrinsic_types`... :cry:

**Comment by kdy1** [comment]
I tried it, and seems like we have a bug in type alias expander or generic expander. The `nom_ty` should not be `S#0`, where #0 means built-in.
So I guess `S#0` comes from the builtin definition of intrinsic like `Uppercase`, and I'm investigating why it is not expanded

**Comment by kdy1** [comment]
<img width="974" alt="image" src="https://user-images.githubusercontent.com/29931815/201512051-3294f6c5-d396-4aea-9451-15a99daae04f.png">

Yeah, the expander was not replacing the type parameter `S#0` for some reason. I'll fix it first.

**Comment by ever0de** [comment]
> <img alt="image" width="974" src="https://user-images.githubusercontent.com/29931815/201512051-3294f6c5-d396-4aea-9451-15a99daae04f.png">
> 
> Yeah, the expander was not replacing the type parameter `S#0` for some reason. I'll fix it first.

thanks to you...!
