### ISSUE TITLE
Handle `this` in computed keys of nested scope

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#234]
We should handle `this` is nested scopes. 

This is required to handle cases like

https://github.com/dudykr/stc/blob/2eadcd5ad1de5e045167ee532e51fc4295b02b7f/crates/stc_ts_type_checker/tests/conformance/es6/computedProperties/computedPropertyNames22_ES6.ts#L1-L9

Currently, we do not use the correct `this`.

https://github.com/dudykr/stc/blob/2eadcd5ad1de5e045167ee532e51fc4295b02b7f/crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs#L2425-L2451

We should add `parent_for_this()` to `Scope` and call it from the code above.

**Comment by iheyunfei** [comment]
I found `scope.this` is not correctly set for `ClssExpr` and `ClassDecl`. though I implement `parent_for_this()`, I still could not get the correct type of `this`.

https://github.com/dudykr/stc/blob/62d01a370ce28b9cbe2878b6293efff888aad4dd/crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs#L1946-L1947

I try to set `scope.this` correctly and found it not easy.

The `ClassDef` type is generated after validating, but to validate `this`, we need `ClassDef` while validating.

**Comment by kdy1** [comment]
Yeah, the evaluation order is always the problem.
stc is written in rust, and rustc really hates shared mutable. We may need to store `RefCell<ClassDef>` in the `Scope`

**Comment by kdy1** [comment]
Closing as fixed by https://github.com/dudykr/stc/pull/580
