### ISSUE TITLE
Pass type annotations to class expressions and class methods

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#302]
# Problem

We should not report `ImplicitAny` for https://github.com/dudykr/stc/blob/e503aa0dc7a553c054046cf64a6ff3d701a44f1b/crates/stc_ts_type_checker/tests/conformance/types/contextualTypes/methodDeclarations/contextuallyTypedClassExpressionMethodDeclaration01.ts#L16-L25

# Solution (guess)

We should pass type annotations to class expressions and use `access_property` to provide type annotations to class methods.

---

I'll expand this if someone is willing to work on this.

**Comment by Max-str** [comment]
I would like to help and try to fix this one.
Could you give some hints on where to start?

My guess would be in the `validate` function of mod.rs in the `RExpr::Class`-Arm of the match.

**Comment by kdy1** [comment]
Yes, your guess is correct. It's the first task.

After that, you should add a type annotation to class member validator at https://github.com/dudykr/stc/blob/e989a804ce806d776ea3148cfcb88e2d06d736e2/crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs#L767

After you add a type annotation to the parameters, IDE will show you problematic code. You should add type annotation there, by using `Analyzer.access_property`.

**Comment by kdy1** [comment]
@Max-str Are you still working on it?

**Comment by Max-str** [comment]
Yes I’m still on it

**Comment by kdy1** [comment]
@Max-str Are you still working on it? If not, please feel free to tell me.

**Comment by camc314** [comment]
@kdy1 Mind assigning it to me?

Should have something to put up in the next few days. (if I don't just unassigned me)

**Comment by kdy1** [comment]
Did it, thank you!
