### ISSUE TITLE
Change error code for overload resolution failure

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#356]
https://github.com/dudykr/stc/blob/5fcf2551ade28eadf83c6c352f8d351f0b717182/crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/overloadResolution.ts#L17-L27

This should fail with `no matching overloads` instead of `argument mismatch`

**Comment by sladyn98** [comment]
@kdy1 Hey any good first issues, would love to contribute, still getting used to rust but I guess I can definitely make some contributions

**Comment by kdy1** [comment]
@sladyn98 There are some issues with `good first issue` label.
https://github.com/dudykr/stc/labels/good%20first%20issue

**Comment by sunrabbit123** [comment]
Fixed it #166 
https://github.com/dudykr/stc/blob/5fcf2551ade28eadf83c6c352f8d351f0b717182/crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/newWithSpreadES6.ts.stats.rust-debug

**Comment by sunrabbit123** [comment]
fixed it #753
