### ISSUE TITLE
Track destructuring

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#552]
```ts
type Data = { kind: 'str', payload: string } | { kind: 'num', payload: number };

function gg2(obj: Data) {
    if (obj.kind === 'str') {
        let t: string = obj.payload;
    }
    else {
        let t: number = obj.payload;
    }
}

function foo({ kind, payload }: Data) {
    if (kind === 'str') {
        let t: string = payload;
    }
    else {
        let t: number = payload;
    }
}
```

Currently, the code above is handled properly, while the below is not. I have thought about this for a while and concluded we should handle this by storing a hashmap like `FxHashMap<Id, FakeName>` in the analyzer.

If you are willing to work on this, I'll try to expand this

---

Ideas:
 - `VarPath` for elements of the fake name.

---

I think looking at the source code of `tsc` would worth the effort.

**Comment by sunrabbit123** [comment]
I will take it, But I can't guarantee it.

**Comment by kdy1** [comment]
You can store an increment-only counter in the `Analyzer` and use it to distinguish patterns. One pattern (object/array) takes one id. Then, you can use it to *connect* identifiers.
