### ISSUE TITLE
Change error code for mixed default exports

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#591]
https://github.com/dudykr/stc/blob/8b5fad3b580e2a4e2a4a75b0e3f45b75a8cc3f63/crates/stc_ts_type_checker/tests/conformance/es6/modules/defaultExportsCannotMerge04.ts#L1-L15

We should report [`TS2652`](https://github.com/microsoft/TypeScript/blob/26eced32ed464c2d31cd6007918224ec0df64c18/src/compiler/diagnosticMessages.json#L2896) instead of `TS2395`

**Comment by filipw01** [comment]
@kdy1 Can I try this one?

**Comment by kdy1** [comment]
Of course, thank you!
