### ISSUE TITLE
Index signature with string indexer should be assignable to one with numeric indexer

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#594]
https://github.com/dudykr/stc/blob/273356f921c6152b5a45c41527923a86361ebe13/crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/typeInference/indexSignatureTypeInference.ts#L1-L17

At the code above, line 17 should pass. i.e. `StringMap<Function>` is assignable to `NumberMap<Function>`.

**Comment by YoniFeng** [comment]
issue can be closed

**Comment by kdy1** [comment]
Thank you!
