### ISSUE TITLE
Use different error code function overload declared with `var` keywords

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#629]
https://github.com/dudykr/stc/blob/9da923ad1557b0ae2866bc449654c190fca1cbce/crates/stc_ts_type_checker/tests/conformance/statements/forStatements/forStatementsMultipleInvalidDecl.ts#L44-L45

```

============================================================
TS2394

  x context: tried to validate signatures of overloaded functions (at crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs:1595:18)
  | context:
  | lhs = (x: number) => string;
  | rhs = (x: string) => number; (at crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs:588:73)
  | context: tried to assign to a function type:  (at crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs:2344:77)
  | context: tried to assign a function to another one (at crates/stc_ts_file_analyzer/src/analyzer/assign/function.rs:439:18)
  | context: tried to assign parameters of a function to parameters of another function (at crates/stc_ts_file_analyzer/src/analyzer/assign/function.rs:374:14)
  | context: tried to assign the type of a parameter to another (at crates/stc_ts_file_analyzer/src/analyzer/assign/function.rs:749:26)
  | context:
  | lhs = number;
  | rhs = string; (at crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs:588:73)
  | context: LHS (final): number;
  | RHS (final): string; (at crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs:1957:25)
  | IncompatibleFnOverload {
  |     span: Span {
  |         lo: BytePos(
  |             680,
  |         ),
  |         hi: BytePos(
  |             681,
  |         ),
  |         ctxt: #0,
  |     },
  |     cause: AssignFailed {
  |         span: Span {
  |             lo: BytePos(
  |                 696,
  |             ),
  |             hi: BytePos(
  |                 697,
  |             ),
  |             ctxt: #0,
  |         },
  |         cause: [],
  |     },
  | }
    ,-[$DIR/tests/conformance/statements/forStatements/forStatementsMultipleInvalidDecl.ts:43:1]
 43 |
 44 | for(var f = F;;){}
    :             ^
 45 | for( var f = (x: number) => '';;){}
    `----

============================================================
```

We currently use `IncompatibleFnOverload` for this case, but it should be [`TS2403`](https://github.com/microsoft/TypeScript/blob/1ed0a5ac4b49971e4698d5388f7760cbaa0615ac/src/compiler/diagnosticMessages.json#L2043-L2046)

**Comment by blacktoast** [comment]
Hello, Do you mind if I try to fix it? As It is my first time on this project, could you recommend any particular document or codes to focus on except [stc/crates/stc_ts_type_checker/tests/conformance/statements/forStatements/forStatementsMultipleInvalidDecl.ts](https://github.com/dudykr/stc/blob/9da923ad1557b0ae2866bc449654c190fca1cbce/crates/stc_ts_type_checker/tests/conformance/statements/forStatements/forStatementsMultipleInvalidDecl.ts#L44-L45)?

**Comment by kdy1** [comment]
It would be nice, thank you!
You can search for code using context. e.g. `tried to validate signatures of overloaded functions` 

https://github.com/dudykr/stc/blob/23dcadee07bcf1bc1d406bf9f6d141e8d079da2e/crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs#L1594-L1624

**Comment by kdy1** [comment]
It's the code responsible for these kinds of errors

**Comment by blacktoast** [comment]
Thank you, I will try it By the way, is this https://github.com/dudykr/stc/blob/main/CONTRIBUTING.md documentation not updated? There's no script written on the document.

**Comment by kdy1** [comment]
FYI, `CONTRIBUTING.md` does not have only a subset of recently added scripts, and it has enough information for contributing.

**Comment by blacktoast** [comment]
Thanks, I'll try it
