### ISSUE TITLE
Ethical concern of this project

### ISSUE THREAD

**Issue by robertpiosik** [dudykr/stc#647]
Hi, looking at where this project is heading to I'm deeply afraid it's _no good_ for the community. Quite poisonous to be honest.

Correct me if I'm wrong but when released in stable, there is no point in using TSC anymore. STC being considerably faster and lighter would make people switch to it and you would gain the power to take control over TS spec.

All this power would come from tons of work on spec design made by people invested in the original TS.

For the sake of the world's peace I'm kindly asking for considering designing your own typed JS syntax and a language server for it and let us see how would your ideas compare to what [Anders Hejlsberg](https://github.com/ahejlsberg) and others came up with.

I wouldn't write this if I knew there is absolutely no chances turning such spectacular task around but I know you're a hard working, smart man capable of achieving it, especially when having support in such large and well prospering enterprise you work for.

**Comment by kdy1** [comment]
I made a poll at https://twitter.com/kdy1dev/status/1623269046623043584 to see how much people agree to you

**Comment by erkobridee** [comment]
I don't see it that way... I remember when a fork for node.js happened in the past, which helped the node.js evolve even more... so I hope that here happens the same with the TSC.

One thing for sure that I know, we need to improve the TSC to be faster. I see this project as an attempt to help TypeScript evolve, and I hope that Microsoft and others join forces to move forward because everyone will win with the outcomes of this project.

That's my 2 cents.

**Comment by gillchristian** [comment]
> Correct me if I'm wrong but when released in stable, there is no point in using TSC anymore. STC being considerably faster and lighter would make people switch to it and you would gain the power to take control over TS spec.

Shouldn't the TSC team worry about that instead?

If anything it should be a good thing that there's competition forcing the project to be held on a higher standard.

**Comment by Jordan-Hall** [comment]
> So we end up with uncoordinated copy what is not ethical (considering international norms, not my own subjective opinions).

If both following the spec it's fine. I've been working on Angular compilers while keeping same implementation for developers. Nothing to this scale but still. Think about ESCMAScript, its  the standard for multiple implementations. Just because the spec writers have written a Implementation, doesn't mean it has to be the only implementation.


If i'm not mistaken, they have already removed some of the work to babel. Tslint went to eslint.

**Comment by erkobridee** [comment]
@robertpiosik I know that's not a fork, but the reason is quite similar, make it move forward like was the intention of io.js and that work wasn't in the hands of the Node Foundation at the beginning...

**Comment by kof** [comment]
@robertpiosik what you described there is based on so many assumptions about how things can go that it's not even funny.

This project, in the best possible scenario, is going to conform to tsc spec as much as possible, just like any transpiler implements javascript, 0 ethical concerns here.

**Comment by kof** [comment]
@robertpiosik I had no idea TS is not actually formalizing the language in a spec document. This is terrible. The more a reason to get a second implementation and eventually come up with a spec.

**Comment by Jordan-Hall** [comment]
Last spec was 1.8. This is kinda bad then, but you can always ensure you pass typescript own test cases. Maybe it bring back the argument for specs https://github.com/Microsoft/TypeScript/issues/15711

**Comment by Xetera** [comment]
The lack of a spec is even more of a reason to get a 2nd implementation going, is it not? If the project has gotten to a point where multiple implementations are desirable then this will push more for an up-to-date spec.

**Comment by kof** [comment]
I hear on twitter that the lack of spec for a language is not unusual and that passing tests is essentially conforming to the spec. As long as stc passes the tests, we are golden.

**Comment by kdy1** [comment]
@robertpiosik  There's no spec, so I can't take control of it.

**Comment by kof** [comment]
@kdy1 is the goal to pass all tests? Are you building it that way?

**Comment by Jordan-Hall** [comment]
> @robertpiosik There's no spec, so I can't take control of it.

And on that note i guess this can be closed as it's theoretically not possible so its not unethical

**Comment by kdy1** [comment]
@kof Yes, but the initial goal is to make type inference correct and to provide faster LSP (mainly to me...)

**Comment by kof** [comment]
> @kof Yes, but the initial goal is to make type inference correct and to provide faster LSP (mainly to me...)

correct in the sense different than tsc? Are we going to run into situation where one ts code doesn't pass with lsp but passes tsc?

**Comment by kdy1** [comment]
@kof  If so it's always a bug of `stc` and I'll fix it

**Comment by kdy1** [comment]
I decided don't care.
Although it was indirect, I tried to make the official TypeScript team participate in a TypeScript implementation. I wasn't interested in being a project lead, but they simply didn't want to participate.

**Comment by Jordan-Hall** [comment]
> Then I'll direct the author of issue to report them to `tsc` instead

And if TSC say it's correct or not however, not going to fix the issue, will you then break the solution in favour of what TSC says?

**Comment by kof** [comment]
I guess it would help this project to be upfront about the conformance and issues like that. To make sure community fully understands the goal and the impact of this project.

**Comment by kdy1** [comment]
Yes, I think it's better. I don't want to split the community. I did the same thing for swc even when `tsc` is a troll. 

(`tsc` does not follow ESM specification. https://github.com/swc-project/swc/issues/5205)

**Comment by kof** [comment]
So goals are:
1. pass all tsc tests
2. if for some reason tsc is wrong can not be fixed, conformance takes priority
3. at all cost avoid splitting community

**Comment by kdy1** [comment]
Yeah, exactly.

**Comment by kdy1** [comment]
It would be a bit different if the TypeScript had a specification, but it's not the case and if so `tsc` itself is the spec.

**Comment by kdy1** [comment]
I documented it at https://stc.dudy.dev/docs/roadmap#goals-regarding-tsc

**Comment by jonasmamona** [comment]
I'm, quite frankly, baffled at this. How could this possibly be unethical? Of course people are going to switch to the better typechecker. That's how things work. Why would someone want to stick to a slower and worse version of the same thing? Why would it be unethical to save people time and money? How dropping this or creating a new language be 'polite to the world'? MS is a nearly 2 trillion dollar corporation, if they care enough, they can make a better typechecker or contribute to this one.

**Comment by jly36963** [comment]
Rust is a much more energy-efficient language than JS/TS. To me, blocking efforts to use a greener/faster/safer language (because of the potential low-probability negative outcomes) seems more unethical.

[Ref](https://medium.com/codex/what-are-the-greenest-programming-languages-e738774b1957)

**Comment by AngeloCore** [comment]
> Soviet Union specialized in copying US stuff, please find some common sense and don't go this path.

It's not that deep. Please don't bring politics into this. **STC** is a competition to **TS**, and competition is always a good thing, it will improve both projects.

**Comment by mtluiz** [comment]
you stupid

**Comment by iamswain25** [comment]
> **If not you, can't you see someone else forking STC and destroying TS nevertheless?**
> 
> Can't you consider employing yourself in MS and working on fast tooling with them or coming up with your own language design ideas? That would be so polite to the world. Excuse me the tone, but I'm just so much against what is being done here and where it all leads. Soviet Union specialized in copying US stuff, please find some common sense and don't go this path.

i find this writing extremely unethical in terms of the open source community. it diminishes diversity and promotes microsoft imperialism. I couldn't help excusing the tone of the totalitarianism and meta-awareness of it being writing on github, backed by microsoft! 😨

**Comment by Thore1954** [comment]
And I thought all the fun is on the bird app!
