### ISSUE TITLE
Change error code for super in a class property based for <= Es5

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#663]
https://github.com/dudykr/stc/blob/94a2b2090d154669348b75f1a40d0899fd90c8a4/crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers9.ts#L8

The expected error is different for Es5. 

See [Es5](https://github.com/dudykr/stc/blob/94a2b2090d154669348b75f1a40d0899fd90c8a4/crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers9(target%3Des5).errors.json) and [Es6](https://github.com/dudykr/stc/blob/94a2b2090d154669348b75f1a40d0899fd90c8a4/crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers9(target%3Des6).errors.json)
 
ES5: 
```
============================================================
TS2660

  x SuperCanBeOnlyReferencedInDerivedClass {
  |     span: Span {
  |         lo: BytePos(
  |             130,
  |         ),
  |         hi: BytePos(
  |             135,
  |         ),
  |         ctxt: #0,
  |     },
  | }
   ,-[$DIR/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers9.ts:7:1]
 7 | class D extends C {
 8 |     static arrowFunctionBoundary = () => super.f + 1;
   :                                          ^^^^^
 9 |     static functionExprBoundary = function () { return super.f + 2 };
   `----

============================================================
1 unmatched errors out of 6 errors. Got 1 extra errors.
Wanted: [RefError { line: 8, column: 48, code: "TS2340" }]
Unwanted: [(8, "TS2660")]
```

**Comment by filipw01** [comment]
I'm on it

**Comment by kdy1** [comment]
Thanks!
