### ISSUE TITLE
I wish there was `extra_error_log.txt`

### ISSUE THREAD

**Issue by sunrabbit123** [dudykr/stc#709]
If there is `extra_error_log.txt`, it will be easy to choose the error you want and work on it.
It is expected that the speed of contribution or work will increase.

**Comment by kdy1** [comment]
Once https://github.com/dudykr/stc/pull/710 is merged, you will be able to run `./scripts/errors/find-extra.sh TS2322` from `stc_ts_type_checker` to find all extra `TS2322` errors.

**Comment by sunrabbit123** [comment]
![image](https://user-images.githubusercontent.com/64676070/219286710-08c58b4e-1d79-4f3b-8d5e-8cf1f2f0386f.png)

**Comment by sunrabbit123** [comment]
I think that add comment to install jq
