### ISSUE TITLE
Default type for an assignment patterns should respect all values

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#720]
https://github.com/dudykr/stc/blob/1cb6c1844cfd2e6b069bddc3588dda51d53a3b6f/crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringWithLiteralInitializers2.ts#L15

Currently `stc` infers the type as `number[]`, but it should be `[number, (string | undefined)]`

**Comment by blacktoast** [comment]
Could I try to fix it?

**Comment by kdy1** [comment]
Of course, thank you!
