### ISSUE TITLE
(TS2555 - ExpectedAtLeastNArgsButGotM) is reported on generator functions without a function call

### ISSUE THREAD

**Issue by awareness481** [dudykr/stc#730]
If you comment out this line

https://github.com/dudykr/stc/blob/ad91d8ac2936f9befb8dbffb43a687b77402318c/crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs#L2213C12-L2215

and run stc on

```ts
// @strict: true

export async function* f3(): AsyncGenerator<any, { x: 'x' }, any> {
    return Promise.resolve({ x: 'x' });
  }
```

you'll see that TS2555 is reported. AFAICT no error should be reported because there's not even a function call. It would be correct to be reported on the following: (imo)

```ts
// @strict: true

export async function* f3(n: number): AsyncGenerator<any, { x: 'x' }, any> {
    return Promise.resolve({ x: 'x' });
  }
  
  f3()
```

**Comment by kdy1** [comment]
Isn't `Promise.resolve()` the function call here?

**Comment by awareness481** [comment]
> Isn't `Promise.resolve()` the function call here?

Oh yeah you're right. I think it makes sense to close the issue then, since the error isn't reported for something like:

```ts
export async function* f3() {
    return 1;
  }
```

**Comment by awareness481** [comment]
Actually I'm having second thoughts, for something like this:

```ts
export async function* f3(): AsyncGenerator<any, { x: 'x' }, any> {
    return Promise.resolve();
  }
```
`stc` reports 2322 and 2555 and `tsc` reports only 2322. So maybe in this case only the assignability of the return statement to the return type should be checked.

But in this case

```ts
async function* f4(x: number, y: string, ...z: any[]): AsyncGenerator<any, { x: 'x' }, any>  {
    // ...
}

export async function* f3(): AsyncGenerator<any, { x: 'x' }, any> {
    return f4(); // TS2555 Expected at least 2 arguments, but got 0.
  }
```

So I guess for an external function the arguments should be checked

**Comment by kdy1** [comment]
Feel free to reopen it if you think it's right to do so
