### ISSUE TITLE
Emit invalid error(want 2471, but 2322)

### ISSUE THREAD

**Issue by sunrabbit123** [dudykr/stc#745]
Do you know this test file? (`tests/conformance/types/typeRelationships/assignmentCompatibility/unionTypesAssignability`)

```ts
class C { }
class D extends C { foo1() { } }
class E extends C { foo2() { } }
var unionDE: D | E;

var num: number;
var str: string;
var c: C;
var d: D;
var e: E;

// A union type U is assignable to a type T if each type in U is assignable to T
c = d;
c = e;
c = unionDE; // ok
d = d;
d = e;
d = unionDE; // error e is not assignable to d
e = d;
e = e;
```
Except for allocations related to the Union,
There is a difference in properties, so it should be 2471.

But stc emit 2322
because the logic returns 2322.

https://github.com/dudykr/stc/blob/main/crates/stc_ts_file_analyzer/src/analyzer/assign/class.rs#L299

I think that we should touch only `assign/mod.rs` and `assign/class.rs`
I think it's an easy issue except for coordinating the order.

**Comment by awareness481** [comment]
Im pretty sure this also depends on https://github.com/dudykr/stc/issues/741

**Comment by sunrabbit123** [comment]
> Im pretty sure this also depends on #741

It'd be nice to combine the two together,
Their internal behavior is different.

**Comment by kdy1** [comment]
I tried this,  but this requires implementing missing property logic for class assignments.
I think we should delegate to type element assign logic, though.

**Comment by kdy1** [comment]
Closed by https://github.com/dudykr/stc/pull/769
