### ISSUE TITLE
Allow extending a class from an interface

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#761]
Relevant test case: https://github.com/dudykr/stc/blob/a02ed2af6607c53dcb7b3628220ac7fc05c78147/crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithObjectMembersAccessibility.ts#L87

```ts
    class Base {
        private foo: string;
    }

    interface I extends Base {
    }

```

should work.

I think this can be done by extending `type_of_ts_entity_name`.

This issue may require more investigation if it is not enough

**Comment by filipw01** [comment]
I can try this one

**Comment by kdy1** [comment]
Is `report_error_for_wrong_interface_inheritance` relevant? I don't think it's a problem.
The issue is about treating them as a parent interface like assigning, not reporting an error for it.
