### ISSUE TITLE
If the union type has `any`,  it should  infer to be `any`

### ISSUE THREAD

**Issue by blacktoast** [dudykr/stc#795]
In this case:
```ts
declare const a: string | any;
a;
```
tsc infers the type of `a` to be `any`.
However, the stc infers it as
```
 1 | declare const a: string | any;
 2 | a;
   : ^
   `----

Error: 
  > (string | any)
```

In my opinion,   The type of `a` should be as tsc infers.

**Comment by blacktoast** [comment]
I will try to fix this issue

**Comment by kdy1** [comment]
Thanks!

**Comment by kdy1** [comment]
Note that there are many cases where `string | any` is different from `any`

**Comment by sunrabbit123** [comment]
if strict true,
priority of union is like next
```ts
type Any = any | string; // any
type Unknown = unknown | string; // unknwon
type Primitive1 = string | never; // string
type Primitive2 = number | never; // number
type Primitive3 = symbol | never; // symbol
type Primitive4 = object | never; // object
type Primitive5 = bigint | never; // bigint
type Primitive6 = boolean | never; // boolean
type Primitive7 = null | never; // null
type Primitive8 = undefined | never; // undefined
type Primitive9 = void | never; // void
type Never = never | never; // never
type InterfaceOrPrimitive = Function & Primitive1; // Object | string
type TypeLiteralOrPrimitive = {} | Primitive1; // string | {}
type Literal1 = "abcd" | Primitive1; // string
type Literal2 = "abcd" | Primitive2; // number | "abcd"
```

This error is because `fn new_union` does not implement it.
I think it will be fixed by adding only simple priorities.

**Comment by blacktoast** [comment]
If the type is `Type::Ref`, is there any way to know the type of that ref? 

I tried to change the `new_union`, but when I changed the logic of the `new_union` to return any, I found that too many places were affected.

So, in `declare_var`, I wanted to return any if the union has any.
But if the type is `Type::Ref`, I don't know how to figure out the type of that ref.

**Comment by awareness481** [comment]
> If the type is `Type::Ref`, is there any way to know the type of that ref?
> 
> I tried to change the `new_union`, but when I changed the logic of the `new_union` to return any, I found that too many places were affected.
> 
> So, in `declare_var`, I wanted to return any if the union has any. But if the type is `Type::Ref`, I don't know how to figure out the type of that ref.

I believe this is the correct way

```rs
match v.normalize() {
   Type::Ref(ref_ty) => {
        if let Ok(ty) = &self.expand_top_ref(ref_ty.span, Cow::Borrowed(v), Default::default()) {
           // ...
        }
    }
}
```

**Comment by sunrabbit123** [comment]
If it's a minimum priority function, I think it's right to put it in even if it's affected.
And this code needs to be replaced.

https://github.com/dudykr/stc/blob/main/crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs#LL365-L370C55
```rs
if types.len() == 1 {
    return Ok(Cow::Owned(types.into_iter().next().unwrap()));
}

 
let ty = Type::Union(Union { types, ..*ty }).freezed();
                     
return Ok(Cow::Owned(ty));
```



like `new_intersection`

What do you think? @kdy1

**Comment by blacktoast** [comment]
My understanding is that I shouldn't modify `union_var` or `declare_var`, but put the logic to check for `any | string` in https://github.com/dudykr/stc/blob/bfeb6fbb6211618e1165eca7710186d6427b2c8e/crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs#L336-L371 
 is that correct?

**Comment by kdy1** [comment]
Yeah, I think so
