### ISSUE TITLE
Improve Interface type params

### ISSUE THREAD

**Issue by awareness481** [dudykr/stc#956]
- [ ] Interface type params not validated
   ```ts
   interface A<T extends string> {}
   type a = A<number> // required error, not reported
   ```
- [x] If two interfaces of the same name and the second one has more type params, there's a panic.
  ```ts
  interface A<T extends string> {}
  interface A<T extends number, U extends number> {}
  type a = A<string, number>; // panics
  ```
  ```rs
  thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', 
  crates/stc_ts_file_analyzer/src/analyzer/decl_merging.rs:109:43
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```

**Comment by awareness481** [comment]
If you agree with the issue, please assign me as I want to try fixing this, thanks ^^

**Comment by kdy1** [comment]
Thank you!

**Comment by sunrabbit123** [comment]
@awareness481 
Are you running `Interface type params not validated`?
I'm getting an error on that part, so I'm guessing you need to assign a worker to it.

The problem is caused by propagating generics and not checking for type.

I think the right place to work on it is in analyzer/generic/mod.rs:122.

If you're working on it, you can use the
How far along are you?

**Comment by awareness481** [comment]
@sunrabbit123 I was actually thinking of removing the assignment from myself because when I tried it I couldn't get it working. Do you want to give it a go yourself? Please feel free to

**Comment by sunrabbit123** [comment]
I've been playing around with it a bit now, and I've found that
Unfortunately, it's working fine, but I'm getting a lot of regressions. 😭

**Comment by sunrabbit123** [comment]
revert this issue
#1029

**Comment by sunrabbit123** [comment]
#1053 

Close the issue because it has been implemented in that location.
