### ISSUE TITLE
Variable initialized with a call expression may not have correct type params inferred

### ISSUE THREAD

**Issue by awareness481** [dudykr/stc#979]
For a variable initialized with a call expression, stc seems to not assign the correct type to the variable.
AFAICT `x` here is inferred as `(a: (a: unknown) => unknown, b: (b: unknown) => unknown, c: (c: unknown) => unknown) => void;`
but should be `<A#3#0, B#3#0, C#3#0>(a: (a: A#3) => A, b: (b: B#3) => B, c: (c: C#3) => C) => void`

```ts
function someGenerics7<A, B, C>(
  a: (a: A) => A,
  b: (b: B) => B,
  c: (c: C) => C
) {}

function someGenerics8<T>(n: T): T {
  return n;
}

var x = someGenerics8(someGenerics7); // return type should be inferred as someGenerics7, as T -> someGenerics7

// stc infers x as (a: (a: unknown) => unknown, b: (b: unknown) => unknown, c: (c: unknown) => unknown) => void; (AFAICT)
// but it should be <A#3#0, B#3#0, C#3#0>(a: (a: A#3) => A, b: (b: B#3) => B, c: (c: C#3) => C) => void

x<string>(null, null, null); // No error from stc, should be 2558 Expected 3 arguments but got 1
```

Edit: If you put a `dbg!(&type_params)` in here https://github.com/dudykr/stc/blob/85361dff709100c1ade4e8415fa2af6665bcc8b5/crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs#L2579

you'll see that the log for the line
`x<string>(null, null, null);`

is `[crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs:2579] &type_params = None` meaning that stc thinks `x` accepts no type parameters

**Comment by awareness481** [comment]
I've tried to solve this and I believe the key is to define a variable's type as the function return type, taking the type args or inferred type args into account, whenever the variable is assigned a call expression. This is kinda hard, I think the solution should be in this file: https://github.com/dudykr/stc/blob/main/crates/stc_ts_file_analyzer/src/analyzer/stmt/var_decl.rs

**Comment by kdy1** [comment]
I'll take a look later today (or this week)
